= Open ID Connect ID Provider

Authenticate your users using Open ID Connect.

This ID Provider application, acting as a OIDC Relying Party. will verify the identity of End-Users based on the authentication performed by your OIDC Authorization Server.
It will redirect unauthenticated users to the Authentication Server and obtain basic information in order to create a user within Enonic XP.
This ID Provider application follows the Authorization Code Flow and uses the Client/Secret POST token auth method.

== Configuration

=== Authorization Server

The configuration depends on the Authorization Server selected and is not covered by this documentation.
It will typically require the creation and configuration of a Client/Application.

==== Authorization Server - Redirection/Callback URI

Once authenticated by the Authorization Server, the End-User will be redirected to Enonic XP.
During the configuration of your Client/Application, you will have to register this callback URL.
The callback URL depends on the VHost mapping and the name of the ID Provider.
It has the following format:  [VHost source]/_/idprovider/[ID Provider name]

Example for a site: https://www.example.com/_/idprovider/myoidcprovider
Example for admin:  https://www.example.com/admin/tool/_/idprovider/myoidcprovider

==== Authorization Server - Information required for the ID Provider Config

You will need to gather the following information for the ID Provider configuration

. The Client ID
. The Client secret
. The Issuer Identifier (URL)
. The Authorization endpoint URL
. The Token endpoint URL

The client credentials are accessible after the creation/configuration of the Client.

You might have been given only the Issuer URL instead of the list of endpoint URLs.
In that case the endpoint URLs are accessible under: [Issuer URL]/.well-known/openid-configuration
The JSON result will contain the required information: "issuer", "authorization_endpoint" and "token_endpoint

Example: Auth0

- OpenID Provider Configuration URL: [Domain URL]/.well-known/openid-configuration
- Issuer Identifier: [Domain URL]/
- Authorization endpoint URL: [Domain URL]/authorize
- Token endpoint URL: [Domain URL]/oauth/token

Example: Google

- OpenID Provider Configuration URL: https://accounts.google.com/.well-known/openid-configuration
- Issuer Identifier: https://accounts.google.com
- Authorization endpoint URL: https://accounts.google.com/o/oauth2/v2/auth
- Token endpoint URL: https://oauth2.googleapis.com/token

Example: Azure AD

- OpenID Provider Configuration URL: https://login.microsoftonline.com/{TenantID}/.well-known/openid-configuration
- Issuer Identifier: https://sts.windows.net/{TenantID}/
- Authorization endpoint URL: https://login.microsoftonline.com/{TenantID}/oauth2/authorize
- Token endpoint URL: https://login.microsoftonline.com/{TenantID}/oauth2/token

Example: Difi/ID-porten/VER1

- OpenID Provider Configuration URL: https://oidc-ver1.difi.no/idporten-oidc-provider/.well-known/openid-configuration
- Issuer Identifier: https://oidc-ver1.difi.no/idporten-oidc-provider/
- Authorization endpoint URL: https://oidc-ver1.difi.no/idporten-oidc-provider/authorize
- Token endpoint URL: https://oidc-ver1.difi.no/idporten-oidc-provider/token


=== Enonic XP


==== Application Installation

. In the admin tool "Applications", click on "Install".
. Select the tab "Enonic Market", find "OIDC ID Provider", and click on the link "Install".

==== ID Provider creation

. In the admin tool "Users", click on "New" and select "Id Provider".
. Fill in the fields and, for the field "Applications", select the application "OIDC ID Provider".
. Configure the ID Provider with the information gathered previously. See <<Enonic XP - ID Provider configuration>> for more information

====  Virtual Host Mapping configuration

. Edit the configuration file "com.enonic.xp.web.vhost.cfg", and set the new user store to your virtual host. (See https://developer.enonic.com/docs/xp/stable/deployment/vhosts[Virtual Host Configuration] for more information).

    mapping.example.host = example.com
    mapping.example.source = /
    mapping.example.target = /portal/master/mysite
    mapping.example.idProvider.myoidcprovider = default

=== Enonic XP - ID Provider configuration

==== Authorization Server

Information mostly found from the OpenID Provider Configuration,
optionally available at the WellKnown endpoint of your Authorization server (/.well-known/openid-configuration).

* Issuer Identifier: Value of "issuer" in your OpenID Provider Configuration
* Authorization endpoint URL: Value of "authorization_endpoint" in your OpenID Provider Configuration
* Token endpoint URL: Value of "token_endpoint" in your OpenID Provider Configuration
* Additional scopes: Scope/Claims to retrieve in addition to the mandatory "openid" scope. We recommend setting the two standard scopes: "profile email".
* User Info Endpoint: If the user information is not returned in the ID Token or incompletely, calls can be made to request user information from additional endpoints
** URL : Endpoint URL. An example could be the value of "userinfo_endpoint" in your OpenID Provider Configuration. But custom endpoints are also possible.
** Enforce Subject Identifier: If the Subject Identifier "sub" is returned, a check can be performed to check the matching values.
* End Session: See <<End Session>> for more information
** End session URL: Value of "end_session_endpoint" in your OpenID Provider Configuration
** ID Token Hint parameter name: "id_token_hint"
** Post Logout Redirect URI parameter name: "post_logout_redirect_uri"

==== Client

This application uses the authentication method "client_secret_post" for the token retrieval
During the creation of your Client/Application, you must have received or generated credentials/secret

* Client Identifier
* Client Secret

==== User Creation

You may configure the values used to created users inside Enonic. The values "${claimKey}" will be replaced by the user information retrieved.
For example a template for display name could be "${given_name} ${family_name}"

* Display name: Template for the display name
* Email: Template for the email
* Default groups: Groups to assign to this user on creation

==== Rules

Additional rules enforced on login

* Enforce Email Verification: Check the claim "email_verified" (returned with the scope "email").


=== End Session

OIDC Front-Channel Logout specifications are still in draft. This might not be supported by your authentication server.
You can check if the endpoint is available in the Open ID Configuration (.well-known/openid-configuration) under the field "end_session_endpoint"
There might also be another custom endpoint available that achieves the same purpose.
The ID Provider Configuration schema tries to be dynamic enough to handle all cases.


Example: Auth0

* End Session URL: [Domain URL]/v2/logout
* Post Logout Redirect URI parameter name: returnTo
* Additional Parameters:
** clientId = [Client ID]

Example: Google

Not available

Example: Azure AD

* End Session URL: https://login.microsoftonline.com/{TenantID}/oauth2/logout
* Post Logout Redirect URI parameter name: post_logout_redirect_uri

Example: Difi/ID-porten/VER1

* End Session URL: https://oidc-ver1.difi.no/idporten-oidc-provider/endsession
* ID Token Hint parameter name: id_token_hint
* Post Logout Redirect URI parameter name: post_logout_redirect_uri













